version: 2

models:
  - name: dim_customers
    description: This table stores customer details enriched with demographic and geographic data.
    columns:
      - name: customer_key 
        description: Unique identifier for each customer
        tests:
          - unique # Check for Uniqueness of Customer Key

  - name: dim_products
    description: This table provides information about the products and their attributes.
    columns:
      - name: product_key
        description: Unique identifier for each product
        tests:
          - unique # Check for Uniqueness of Product Key
    