version: 2

sources:
    - name: sales_db
      schema: raw
      tables:
        - name: crm_customers
          identifier: crm_cust_info

        - name: crm_products
          identifier: crm_prd_info

        - name: crm_sale_details
          identifier: crm_sales_details

        - name: erp_customer_locations
          identifier: erp_loc_a101

        - name: erp_customers
          identifier: erp_cust_az12